// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";

function parse($$char, stream) {
  if (!stream) {
    return {
            TAG: /* Error */1,
            _0: "end of stream"
          };
  }
  var tail = stream.tl;
  var only = stream.hd;
  if (tail) {
    return {
            TAG: /* Ok */0,
            _0: [
              only,
              tail
            ]
          };
  } else {
    return {
            TAG: /* Ok */0,
            _0: [
              only,
              /* [] */0
            ]
          };
  }
}

function run($$char, arr) {
  var partial_arg = Belt_List.fromArray(arr);
  return function (param) {
    return parse(partial_arg, param);
  };
}

export {
  parse ,
  run ,
}
/* No side effect */
