// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Belt_List from "rescript/lib/es6/belt_List.js";

function parse($$char, stream) {
  if (!stream) {
    return {
            TAG: /* Error */1,
            _0: "end of stream"
          };
  }
  var tail = stream.tl;
  var only = stream.hd;
  if (tail) {
    return {
            TAG: /* Ok */0,
            _0: [
              only,
              tail
            ]
          };
  } else {
    return {
            TAG: /* Ok */0,
            _0: [
              only,
              undefined
            ]
          };
  }
}

function run($$char, arr) {
  if (arr.length === 0) {
    return {
            TAG: /* Error */1,
            _0: "end of stream"
          };
  } else {
    return parse($$char, Belt_List.fromArray(arr));
  }
}

var Parser = {
  parse: parse,
  run: run
};

export {
  Parser ,
}
/* No side effect */
