// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Zora from "@dusty-phillips/rescript-zora/src/Zora.bs.mjs";
import * as Zora$1 from "zora";
import * as Telnet$DwApi from "../Telnet.bs.mjs";

Zora$1.test("base cases", (function (t) {
        var eof = Telnet$DwApi.Parser.run(1, []);
        Zora.resultError(t, eof, "error result");
        var single = Telnet$DwApi.Parser.run(1, [0]);
        Zora.resultOk(t, single, (function (t, expected) {
                t.equal(expected, [
                      0,
                      undefined
                    ], "single element");
              }));
        var more = Telnet$DwApi.Parser.run(1, [
              2,
              3,
              4
            ]);
        Zora.resultOk(t, more, (function (t, expected) {
                t.equal(expected, [
                      2,
                      {
                        hd: 3,
                        tl: {
                          hd: 4,
                          tl: /* [] */0
                        }
                      }
                    ], "multiple elements");
              }));
        return Zora.done(undefined);
      }));

var Telnet;

export {
  Telnet ,
}
/*  Not a pure module */
